### ISSUE TITLE
add dissemination Page

### ISSUE THREAD

**Issue by ragarwa2** [GarvitaBajaj/Sarathi-Project#6]
Good to add a dissemination page with pictures.

**Comment by ragarwa2** [comment]
@GarvitaBajaj: Project outreach is only shown available in the home page header not in other pages header.

**Comment by GarvitaBajaj** [comment]
I can see the Project Outreach tab in every page's header. Since the branch
has now been merged, can you check once again on
http://garvitabajaj.github.io/Sarathi-Project.

--Regards
Garvita Bajaj
IIIT-Delhi
